language: smalltalk

install:
  - pip install --user benchupload

os:
  - linux
  - osx

smalltalk:
  - Pharo-6.0 we disable because of issue #32
#  - Pharo-alpha

env:
  - REVISION="$(if [[ ${TRAVIS_TAG}tag = tag ]] ; then date -u +%Y%m%d-${TRAVIS_BUILD_NUMBER} ; else echo ${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER} ; fi)"

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mosquitto mosquitto-clients ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mosquitto ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start mosquitto ; fi
#   - mosquitto_pub -h localhost -p 1883 -t abc -m 'checking mosquitto connection'

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/before-deploy.sh ; fi
  
deploy:
  - provider: bintray
    skip_cleanup: true
    file: .bintray.json
    user: $BINTRAY_USER
    key: $BINTRAY_API_KEY
    on: 
      branch: master
      repo: JurajKubelka/PharoSprint
      condition:  "$TRAVIS_OS_NAME = linux"
  - provider: bintray
    skip_cleanup: true
    file: .bintray.json
    user: $BINTRAY_USER
    key: $BINTRAY_API_KEY
    on: 
      tags: true
      repo: JurajKubelka/PharoSprint
      condition:  "$TRAVIS_OS_NAME = linux"
