language: smalltalk
# sudo: true

install:
  - pip install --user benchupload

os:
  - linux
#  - osx

smalltalk:
  - Pharo-6.0

env:
  - REVISION="$(date -u +%Y%m%d%H%M%S)-$TRAVIS_BUILD_NUMBER"

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mosquitto mosquitto-clients ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mosquitto ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start mosquitto ; fi
#   - mosquitto_pub -h localhost -p 1883 -t abc -m 'checking mosquitto connection'

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD

before_deploy:
  - cp $SMALLTALK_CI_BUILD/TravisCI.image PharoSprint.image
  - cp $SMALLTALK_CI_BUILD/TravisCI.changes PharoSprint.changes

deploy:
  provider: bintray
  skip_cleanup: true
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  on: 
    branch: master
    repo: JurajKubelka/PharoSprint
    condition:  "$TRAVIS_OS_NAME = linux"
