language: smalltalk
# sudo: true

install:
  - pip install --user benchupload

os:
  - linux
  - osx

smalltalk:
  - Pharo-6.0

env:
  - REVISION="$(date -u +%Y%m%d%H%M)-$TRAVIS_BUILD_NUMBER"

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mosquitto mosquitto-clients ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mosquitto ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start mosquitto ; fi
#   - mosquitto_pub -h localhost -p 1883 -t abc -m 'checking mosquitto connection'

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD

before_deploy:
  # build image and change files and compress them into one ZIP file
  - ( cd scripts && ./build.sh -6cz -n PharoSprint )
  # set version and commit id for the bintray configuration
  - sed -i.bak -e 's/$Rev\$/'"$REVISION"'/' -e  's/$Commit\$/'"$TRAVIS_COMMIT"'/' -e 's/CommitMessage\$/'"$TRAVIS_COMMIT_MESSAGE"'/' .bintray.json
  
deploy:
  provider: bintray
  skip_cleanup: true
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  on: 
    branch: master
    repo: JurajKubelka/PharoSprint
    condition:  "$TRAVIS_OS_NAME = linux"
