catalog
catalogDescription
	^ 'The Pharo community regularly organize Pharo Sprint events. The Pharo Sprint is a regular (monthly) event when developers and users meet together to fix bugs. This usually takes place in a physical location, but people are welcomed to participate from any place. This is a great opportunity for novices to get involved and learn from experts!

For more information: http://bit.ly/SprintWeb and http://pharo.org/contribute-events'
